package com.swjtu.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_tbl.id
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_tbl.dept_name
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_tbl.id
     *
     * @return the value of dept_tbl.id
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_tbl.id
     *
     * @param id the value for dept_tbl.id
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_tbl.dept_name
     *
     * @return the value of dept_tbl.dept_name
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_tbl.dept_name
     *
     * @param deptName the value for dept_tbl.dept_name
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}