package com.swjtu.mybatis.dao;

import com.swjtu.mybatis.bean.Department;
import java.util.List;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int updateByPrimaryKey(Department record);
}