package com.swjtu.mybatis.dao;

import com.swjtu.mybatis.bean.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_tbl
     *
     * @mbg.generated Wed Jul 18 07:04:51 CST 2018
     */
    int updateByPrimaryKey(Employee record);
}